# Basic
title: Vivian Wong
#subtitle: A blog-orientation theme for Jekyll
welcome_message: Recently, I interned at Alibaba Cloud, where I worked under the <a href="https://www.alibabacloud.com/et/city"><font color="85C1E9"><u>City Brain Project</u></font></a> to develop intelligent traffic signal control algorithms. 
description: Hi! I am a graduate student at Stanford University studying Civil Engineering. My interests are in solving critical societal and urban problems with the help of computational methods such as digital simulation and AI.
#creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vivian-wong.github.io"

permalink: /:year/:month/:title/

# Format
# TO DO: CHANGE HIGHLIGHTER COLOR
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# Navigation buttons in the front page.
nav:
#    - {title: About, url: '/'} # if new window, add target
    - {title: Curriculum Vitae, url: 'assets/pdfs/CV.pdf', target: '_blank'}
    - {title: Projects, url: '/'}
#    - {title: Publications, description: Publications, url: 'http://example.com'}
    
# The blog button should not be removed.
blog_button:
    title: Blog

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
#    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
#    weibo: onevcat
    github: vivian-wong
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: vwwong3@stanford.edu

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
